export const FETCH_MOVIE = 'FETCH_MOVIE'
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS'
export const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR'

export const FETCH_LATEST_MOVIE = 'FETCH_LATEST_MOVIE'
export const FETCH_LATEST_MOVIE_SUCCESS = 'FETCH_LATEST_MOVIE_SUCCESS'
export const FETCH_LATEST_MOVIE_ERROR = 'FETCH_LATEST_MOVIE_ERROR'

export const FETCH_MOVIE_DETAIL = 'FETCH_MOVIE_DETAIL'
export const FETCH_MOVIE_DETAIL_SUCCESS = 'FETCH_MOVIE_DETAIL_SUCCESS'
export const FETCH_MOVIE_DETAIL_ERROR = 'FETCH_MOVIE_DETAIL_ERROR'
export const RESET_MOVIE_DETAIL = 'RESET_MOVIE_DETAIL'
