export const FETCH_VIDEO_DETAIL = 'FETCH_VIDEO_DETAIL'
export const FETCH_VIDEO_DETAIL_SUCCESS = 'FETCH_VIDEO_DETAIL_SUCCESS'
export const FETCH_VIDEO_DETAIL_ERROR = 'FETCH_VIDEO_DETAIL_ERROR'
export const RESET_VIDEO_DETAIL = 'RESET_VIDEO_DETAIL'
