export const FETCH_PLAYER_DETAIL = 'FETCH_PLAYER_DETAIL'
export const FETCH_PLAYER_DETAIL_SUCCESS = 'FETCH_PLAYER_DETAIL_SUCCESS'
export const FETCH_PLAYER_DETAIL_ERROR = 'FETCH_PLAYER_DETAIL_ERROR'
export const RESET_PLAYER_DETAIL = 'RESET_PLAYER_DETAIL'
